- CHANGELOG.md
- Dependiject/XUI/Store.swift
- iOS 13 Example/Dependiject/ContentView.swift
- iOS 13 Example/Dependiject/ContentViewModel.swift
- iOS 13 Example/Dependiject/Services.swift
- iOS 13 Example/Tests/Tests.swift
- iOS 14 Example/Dependiject_Example/ContentView.swift
- iOS 14 Example/Dependiject_Example/ContentViewModel.swift
- iOS 14 Example/Dependiject_Example/Services.swift
- iOS 14 Example/Dependiject_ExampleTests/Tests.swift
Fixes #11
This PR adds an optional Scheduler argument to `@Store` which defaults to `RunLoop.main`, so the user can specify where to receive updates.
I'm not 100% sure on the licensing implications, see the issue for details.
The example apps have been changed so this is now necessary. If you change the code so that the view does not receive updates on the main thread, either by reverting the changes to `@Store` or by modifying the view as follows:
```diff
import SwiftUI
import Dependiject
+import Combine
struct ContentView: View {
-    @Store var viewModel = Factory.shared.resolve(ContentViewModel.self)
+    @Store(on: ImmediateScheduler.shared) var viewModel = Factory.shared.resolve(ContentViewModel.self)
```
then clicking the "fetch new data" button will cause a runtime warning not to …
> Make @Store default to RunLoop.main

- CHANGELOG.md
- iOS 13 Example/Dependiject.xcodeproj/project.pbxproj
- iOS 13 Example/Dependiject/AppDelegate.swift
- iOS 13 Example/Dependiject/ContentView.swift
- iOS 13 Example/Dependiject/Models.swift
- iOS 13 Example/Dependiject/PrimaryView.swift
- iOS 13 Example/Dependiject/PrimaryViewModel.swift
- iOS 13 Example/Dependiject/SecondaryView.swift
- iOS 13 Example/Dependiject/SecondaryViewModel.swift
- iOS 13 Example/Dependiject/Services.swift
- iOS 13 Example/MockingbirdSupport/Combine/ObservableObjectPublisher.swift
- iOS 13 Example/MockingbirdSupport/Dependiject/AnyObservableObject.swift
- iOS 13 Example/Tests/PrimaryViewModelTests.swift
- iOS 13 Example/Tests/SecondaryViewModelTests.swift
- iOS 14 Example/Dependiject_Example.xcodeproj/project.pbxproj
- iOS 14 Example/Dependiject_Example/ContentView.swift
- iOS 14 Example/Dependiject_Example/Dependiject_ExampleApp.swift
- iOS 14 Example/Dependiject_Example/Models.swift
- iOS 14 Example/Dependiject_Example/PrimaryView.swift
- iOS 14 Example/Dependiject_Example/PrimaryViewModel.swift
- iOS 14 Example/Dependiject_Example/SecondaryView.swift
- iOS 14 Example/Dependiject_Example/SecondaryViewModel.swift
- iOS 14 Example/Dependiject_Example/Services.swift
- iOS 14 Example/Dependiject_ExampleTests/PrimaryViewModelTests.swift
- iOS 14 Example/Dependiject_ExampleTests/SecondaryViewModelTests.swift
- iOS 14 Example/MockingbirdSupport/Combine/ObservableObjectPublisher.swift
- iOS 14 Example/MockingbirdSupport/Dependiject/AnyObservableObject.swift
Fixes #7 
This PR adds an example for Mocking a protocol that extends `AnyObservableObject`, and refactors view / viewModel code to make the example tests meaningful.
> added example for testing protocols that extend AnyObservableObject

- CHANGELOG.md
- README.md
- docserver/index.js
Fixes #15
Rather than always running on port 3000, the documentation server now runs on the port specified by the `DOC_PORT` environment variable. See the README for an example.
If the port is specified as 0, or not specified at all, hapi will search for an available port.
The `??` operator in JavaScript was introduced in node 14, and the documentation server is compatible with node 12. To avoid breaking node 12 compatibility, I have used `||` instead.
It appears that hapi 21 will require node 14 anyways, so if and when we upgrade from hapi 20 to hapi 21, this `||` can be changed to `??`. 
Run the dochost script in the terminal with various values for `DOC_PORT`.
> Allow documentation to run on any port

- CHANGELOG.md
- Dependiject.podspec
- README.md
Fixes #19
This PR updates the README to mention that the documentation is hosted online, and adds a `documentation_url` to the podspec.
N/A
N/A
> Reference online documentation

- .github/ISSUE_TEMPLATE/bug-report.md
Fixes #22
This PR changes the version numbers in the bug report template from actual version numbers (like `1.11.3`) to `x.y.z`, so that it doesn't have to be continually updated as new versions of other software are released.
N/A
N/A
> Change version numbers in the bug report template to x.y.z

- CHANGELOG.md
- Dependiject/Factory.swift
- iOS 13 Example/Podfile.lock
- iOS 14 Example/Podfile.lock
Fixes #25
This PR adds the ability to track dependency resolution depth. If the depth exceeds a certain amount (100 by default), the program may terminate, depending on the error-checking mode (by default, this is only for debug builds and not release builds).
N/A
This can't be tested automatically, since it would crash the test runner. However, examples of what should trigger this check are present in the documentation and in the linked issue.
> Add check for circular dependencies

- CHANGELOG.md
- Dependiject/Store.swift
- Package.resolved
- Package.swift
- Tests/StoreTests.swift
Fixes #29
This PR adds automated tests for `@Store`, as outlined in the issue. One of its properties was changed from `private` to `internal` so it could be accessed in the tests.
This does add an external dependency, on [Entwine][1]. Some alternatives considered:
- [combine-schedulers][2], which is more active, but also requires Swift 5.5. Using this would delay this PR from version 0.2.1 to 1.0.0.
- [SchedulerKit][3], which hasn't been updated in over a year and isn't as well-documented as the other two.
The `Package.resolved` file is the lockfile, akin to `Podfile.lock` or `yarn.lock`.
Run the tests in Xcode or with `swift test`.
[1]: https://github.com/tcldr/Entwine
[2]: https://github.com/pointfreeco/combine-schedulers
[3]: https://github.com/scheduler-kit/SchedulerKit
> Add automated tests for @Store

- CHANGELOG.md
- iOS 13 Example/Dependiject/PrimaryView.swift
- iOS 14 Example/Dependiject_Example/PrimaryView.swift
Fixes #27
This PR changes what is displayed when the list is empty on iOS 16. It also adds padding to the "Confirm Data" button, as it was very close to the bottom safe area.
N/A
This should be tested both in Xcode 14 and in some earlier version of Xcode, to ensure that the project compiles even as it references an iOS version Xcode may not know about.
I have tested it locally on the iOS 16 simulator, and it appears to work as intended:
> Fix example projects for iOS 16

- CHANGELOG.md
- README.md
- iOS 13 Example/Dependiject.xcodeproj/project.pbxproj
- iOS 14 Example/Dependiject_Example.xcodeproj/project.pbxproj
- runtests.sh
Fixes #31
This PR adds a script to run all tests, including the example projects' tests, from the command line. It also entails a change to the pbxproj files to allow the test script to generate mocks automatically.
N/A
Run the test script.
> Run all tests

- CHANGELOG.md
- Dependiject/MultitypeService.swift
- Dependiject/Registration.swift
- Dependiject/RegistrationConvertible.swift
- Tests/DuplicateRegistrationTest.swift
- Tests/MultitypeServiceTests.swift
- Tests/RegistrationNameTests.swift
- Tests/ScopeTests.swift
- iOS 13 Example/Tests/PrimaryViewModelTests.swift
- iOS 14 Example/Dependiject_ExampleTests/PrimaryViewModelTests.swift
Fixes #21 
This PR adds the `ConstantRegistration` type, and new initializers to `Service` and `MultitypeService`, to register existing objects as dependencies.
For better organization, I changed `TransientRegistration` to a struct (as noted in the **`Remark`** above it) and put it next to `ConstantRegistration`. This looks a little weird in the diff.
I added new tests to check the new initializers, in the same format as the existing tests. Some of the tests for which scope is less important (such as the registration name tests) I also changed to use this.
> Add registration of external constants

- CHANGELOG.md
- Dependiject.podspec
- Dependiject/Factory.swift
- README.md
- Tests/ParallelResolutionTest.swift
- iOS 13 Example/Podfile.lock
- iOS 14 Example/Podfile.lock
Fixes #35 
This PR protects the methods of `Factory` with an `NSRecursiveLock`. This ensures that it can safely be called from any thread.
This PR is meant as a more user-friendly and both backwards- and forwards-compatible alternative to #36. As it turns out, Swift concurrency is not required to solve the problem.
Try to call `Factory.register` and `Factory.shared.resolve` in various ways in concurrent contexts. I was unable to get it to break.
> Make Factory thread-safe using NSRecursiveLock

- CHANGELOG.md
- Dependiject/RegistrationConvertible.swift
- Tests/RegistrationNameTests.swift
- Tests/ScopeTests.swift
Fixes #39
This PR makes the `name` argument to the Service initializer require a label, to better match the resolve function.
N/A
N/A
> Make name argument labeled

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- dochost.sh
- runtests.sh
Fixes #50
This PR adds a dependency on xcpretty, and pipes the output of `xcodebuild` to that.
If you don't already have xcpretty installed, the test and documentation scripts automatically install it. This may require you to enter your password into the terminal.
Run the test or documentation script and note the significantly reduced output:
```zsh
% ./runtests.sh 2>&1 | wc                     
115     683    7913
```
That is, it outputs 115 lines; 683 words; 7913 bytes. Compare this to the count in the linked issue.
> Add xcpretty

- CHANGELOG.md
- Dependiject/Factory.swift
- Dependiject/Registration.swift
- Tests/ScopeTests.swift
Fixes #32
This PR adds a check for resolving a weak service as a dependency for a singleton. Such a resolution promotes the weak service to itself be a singleton, unless the singleton stores it in a weak property.
Since it is possible for this to work as declared, it is possible to opt out of the check.
I'm not completely satisfied with how `WeakRegistration` accesses the options. I'm open to suggestions in this regard.
Removing the line `Factory.options.singletonAcceptsWeak = true` from the new test should cause it to crash, unless `Factory.options.mode` is set to `.never`.
> Add error for weak service resolved by singleton

- CHANGELOG.md
- Dependiject.podspec
- Dependiject/Factory.swift
- Dependiject/Store.swift
- Package.swift
- README.md
- Tests/StoreTests.swift
- iOS 13 Example/Dependiject.xcodeproj/project.pbxproj
- iOS 13 Example/Podfile.lock
- iOS 14 Example/Podfile.lock
Fixes #38
This PR makes a slight adjustment to the `@Store` property wrapper to follow Swift's concurrency rules. However, this also requires Swift 5.5 or later, so both the code and documentation have been updated accordingly.
While the `nonisolated` keyword isn't strictly required, adding that with no other changes upgrades this problem from an opt-in warning to a guaranteed error.
I didn't enable the `-warn-concurrency` flag because it warns about accesses to `Factory.options`. ~~However, I left it commented-out in Package.swift, so you can easily un-comment it to enable the warning.~~
Edit: I will remove the comment from Package.swift. To enable the flag, add the following lines to the target:
```diff
.target(
name: "Dependiject",
path: "Dependiject",
+            swiftSettings: [
+ …
```
> Fix @Store concurrency

- CHANGELOG.md
- Dependiject/Factory.swift
- Tests/BaseFactoryTest.swift
- Tests/DuplicateRegistrationTest.swift
- Tests/MultitypeServiceTests.swift
- Tests/ParallelResolutionTest.swift
- Tests/RegistrationNameTests.swift
- Tests/ScopeTests.swift
- Tests/StoreTests.swift
- iOS 13 Example/Tests/PrimaryViewModelTests.swift
- iOS 14 Example/Dependiject_ExampleTests/PrimaryViewModelTests.swift
Fixes #52
This PR adds a static method `clearDependencies()` to the factory, and calls it at the start of each test that uses the factory.
N/A
Checking the factory's `registrations` array at the start of a test (e.g. with a breakpoint) should always show an empty array. On master, it is not empty if another test method has already been called as part of the same test run (e.g. running the whole test class rather than just one test method).
> Add clearDependencies method to Factory

- CHANGELOG.md
- Dependiject/Resolver.swift
Fixes #54 
Jira issue: [THOS-5](https://tinyhomeconsultingllc.atlassian.net/browse/THOS-5)
This PR fixes type resolution errors. Basically, what would happen in a situation like this:
```swift
protocol P {}
class C: P {
init(a: Int, c: String) {}
}
func setup() {
Factory.register { // [1]
Service(.transient, P.self) { r in
C(
a: r.resolve(),
b: r.resolve(), // [2]
c: r.resolve()
)
}
}
}
```
is that Swift would be unable to figure out the generic type argument to `r.resolve()` at [2], since the initializer for `C` doesn't take a `b`. Because it can't determine the return type, swift would report "type of expression is ambiguous without more context", completely ignoring the fact that it's not meant to be there. Due to the result builder transform, the error would be reported at [1] instead …
> Fix unhelpful type error

- CHANGELOG.md
- Dependiject.podspec
- Gemfile
- README.md
- iOS 13 Example/Podfile.lock
- iOS 14 Example/Podfile.lock
Fixes #57
Jira issue: https://tinyhomeconsultingllc.atlassian.net/browse/THOS-6
This PR bumps the required CocoaPods version from 1.10.0 to 1.11.3.
N/A
N/A
> Bump required CocoaPods version

- CHANGELOG.md
- Dependiject/Store.swift
Fixes #62 
https://tinyhomeconsultingllc.atlassian.net/browse/THOS-14
Changes the default scheduler for the `@Store` property wrapper from `RunLoop.main` to `DispatchQueue.main`.
It's a smaller PR but let me know if I failed to update all the necessary documentation etc.
The example apps will work almost exactly the same. On a smaller device, you may be to manipulate the scroll view to see the difference between button actions while it's scrolling. But really, it's cases like the one linked in the issue that this matters the most for.
> store-schedule-dispatch-main

- CHANGELOG.md
- Dependiject/Factory.swift
- Dependiject/Registration.swift
- Tests/ParallelResolutionTest.swift
- Tests/ScopeTests.swift
Fixes #65 
https://tinyhomeconsultingllc.atlassian.net/browse/THOS-17
This PR changes how the factory's options can be accessed, allowing for better control and thread-safety.
N/A
See the new test for mutating the options concurrently. Previously, these were implemented as pairs of get/set operations, and if these operations were interleaved, the total result at the end would be less than expected.
> Restrict access to factory options

- CHANGELOG.md
- Dependiject/MultitypeService.swift
Fixes #66
https://tinyhomeconsultingllc.atlassian.net/browse/THOS-18
This PR changes the public-facing iterator type from `IndexingIterator` to `AnyIterator`.
N/A
N/A
> Change MultitypeService.Iterator

- CHANGELOG.md
- Dependiject/Factory.swift
- Dependiject/RegistrationConvertible.swift
Fixes #67
https://tinyhomeconsultingllc.atlassian.net/browse/THOS-19
This PR wraps the `Scope` enum in a struct, so that adding new cases is not a breaking change.
`ErrorCheckMode` was implicitly hashable, I just made it explicit.
Switch over a variable typed `Scope`. You should be allowed to have `case .weak`, `case .transient`, and `case .singleton` branches, but required to have a `default` branch.
> Wrap Scope enum in struct

- Dependiject/Factory.swift
Fixes #71
https://tinyhomeconsultingllc.atlassian.net/browse/THOS-20
This PR adds `Resolver` to the list of protocols adopted by `Factory`, so that it is visible even when the internal protocol is not.
This doesn't require a changelog entry, since the thing it changes was never present in an actual release.
- If you have the autogenerated header open from another branch, close it and clean the build folder.
- Rebuild the test/example project you used to see the autogenerated header.
- Open the autogenerated header again. It should now say:
```swift
final public class Factory : Dependiject.Resolver, @unchecked Sendable {
```
> Add Resolver to Factory's protocol list

- CHANGELOG.md
- Dependiject/Factory.swift
- Dependiject/Resolver.swift
- Tests/DuplicateRegistrationTest.swift
- Tests/RegistrationNameTests.swift
Fixes #64
https://tinyhomeconsultingllc.atlassian.net/browse/THOS-15
This PR adds the resolveAll method as a requirement of Resolver, and an implementation of it in the factory.
This method could afford to be better-documented, but it's niche enough that I don't think it belongs in the sample apps. Contextless examples (like what currently exist for `Registration`, `MultitypeService`, etc) may not be particularly useful.
See the docs and tests.
> Add resolveAll() to Resolver

- CHANGELOG.md
- Dependiject/MultitypeService.swift
- Tests/MultitypeServiceTests.swift
Fixes #56
https://tinyhomeconsultingllc.atlassian.net/browse/THOS-21
This PR adds the ability to give names to dependencies that are registered with `MultitypeService`.
I don't like that `RegistrationTypeList.getName(for:)` returns an optional of an optional, but I'm not sure what more idiomatic return type there would be. It's on an `internal func` at least, so it's not public API.
Register and resolve named and unnamed dependencies that are created under `MultitypeService`. If the array/dictionary passed to the init doesn't list a certain type, you shouldn't be able to resolve the object as that type even if the type matches at runtime.
> Named multitype service

- CHANGELOG.md
- Dependiject/MultitypeService.swift
- Dependiject/Registration.swift
- Dependiject/Util.swift
Fixes #76 
https://tinyhomeconsultingllc.atlassian.net/browse/THOS-22
This PR restructures `SingletonRegistration` to release the closure once the object is instantiated.
N/A
Run a sample app and wait for the first view (after the splash screen) to appear. Then, use the memory graph to ensure the `SingletonRegistration` does not hold a reference to a "Swift closure context".
> Restructure SingletonRegistration
